name: semantic-segmentation
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - argon2-cffi=21.3.0=pyhd3eb1b0_0
  - argon2-cffi-bindings=21.2.0=py38h2bbff1b_0
  - asttokens=2.0.5=pyhd3eb1b0_0
  - attrs=21.4.0=pyhd3eb1b0_0
  - backcall=0.2.0=pyhd3eb1b0_0
  - beautifulsoup4=4.11.1=py38haa95532_0
  - blas=1.0=mkl
  - bleach=4.1.0=pyhd3eb1b0_0
  - brotli=1.0.9=h8ffe710_7
  - brotli-bin=1.0.9=h8ffe710_7
  - brotlipy=0.7.0=py38h2bbff1b_1003
  - ca-certificates=2022.4.26=haa95532_0
  - certifi=2021.10.8=py38haa95532_2
  - cffi=1.15.0=py38h2bbff1b_1
  - charset-normalizer=2.0.4=pyhd3eb1b0_0
  - colorama=0.4.4=pyh9f0ad1d_0
  - cryptography=36.0.0=py38h21b164f_0
  - cudatoolkit=11.3.1=h59b6b97_2
  - cycler=0.11.0=pyhd8ed1ab_0
  - debugpy=1.5.1=py38hd77b12b_0
  - decorator=5.1.1=pyhd3eb1b0_0
  - defusedxml=0.7.1=pyhd3eb1b0_0
  - entrypoints=0.4=py38haa95532_0
  - executing=0.8.3=pyhd3eb1b0_0
  - fonttools=4.33.3=py38h294d835_0
  - freeglut=3.2.2=h0e60522_1
  - freetype=2.10.4=hd328e21_0
  - hdf5=1.10.4=h7ebc959_0
  - icc_rt=2019.0.0=h0cc432a_1
  - icu=58.2=ha925a31_3
  - idna=3.3=pyhd3eb1b0_0
  - importlib_resources=5.2.0=pyhd3eb1b0_1
  - intel-openmp=2021.4.0=haa95532_3556
  - ipykernel=6.9.1=py38haa95532_0
  - ipython=8.3.0=py38haa95532_0
  - ipython_genutils=0.2.0=pyhd3eb1b0_1
  - ipywidgets=7.6.5=pyhd3eb1b0_1
  - jbig=2.1=h8d14728_2003
  - jedi=0.18.1=py38haa95532_1
  - jinja2=3.0.3=pyhd3eb1b0_0
  - jpeg=9b=hb83a4c4_2
  - jsonschema=4.4.0=py38haa95532_0
  - jupyter=1.0.0=py38_7
  - jupyter_client=7.2.2=py38haa95532_0
  - jupyter_console=6.4.3=pyhd3eb1b0_0
  - jupyter_core=4.10.0=py38haa95532_0
  - jupyterlab_pygments=0.1.2=py_0
  - jupyterlab_widgets=1.0.0=pyhd3eb1b0_1
  - kiwisolver=1.4.2=py38hbd9d945_1
  - lerc=3.0=h0e60522_0
  - libblas=3.9.0=1_h8933c1f_netlib
  - libbrotlicommon=1.0.9=h8ffe710_7
  - libbrotlidec=1.0.9=h8ffe710_7
  - libbrotlienc=1.0.9=h8ffe710_7
  - libcblas=3.9.0=5_hd5c7e75_netlib
  - libclang=13.0.1=default_h81446c8_0
  - libdeflate=1.10=h8ffe710_0
  - liblapack=3.9.0=5_hd5c7e75_netlib
  - liblapacke=3.9.0=5_hd5c7e75_netlib
  - libopencv=4.0.1=hbb9e17c_0
  - libpng=1.6.37=h2a8f88b_0
  - libprotobuf=3.20.1=h7755175_0
  - libtiff=4.2.0=hd0e1b90_0
  - libuv=1.40.0=he774522_0
  - libwebp=1.2.2=h2bbff1b_0
  - libwebp-base=1.2.2=h8ffe710_1
  - libzlib=1.2.11=h8ffe710_1014
  - lz4-c=1.9.3=h2bbff1b_1
  - m2w64-gcc-libgfortran=5.3.0=6
  - m2w64-gcc-libs=5.3.0=7
  - m2w64-gcc-libs-core=5.3.0=7
  - m2w64-gmp=6.1.0=2
  - m2w64-libwinpthread-git=5.0.0.4634.697f757=2
  - markupsafe=2.0.1=py38h2bbff1b_0
  - matplotlib=3.5.2=py38haa244fe_0
  - matplotlib-base=3.5.2=py38he529843_0
  - matplotlib-inline=0.1.2=pyhd3eb1b0_2
  - mistune=0.8.4=py38he774522_1000
  - mkl=2021.4.0=haa95532_640
  - mkl-service=2.4.0=py38h2bbff1b_0
  - mkl_fft=1.3.1=py38h277e83a_0
  - mkl_random=1.2.2=py38hf11a4ad_0
  - msys2-conda-epoch=20160418=1
  - munkres=1.1.4=pyh9f0ad1d_0
  - nbclient=0.5.13=py38haa95532_0
  - nbconvert=6.4.4=py38haa95532_0
  - nbformat=5.3.0=py38haa95532_0
  - nest-asyncio=1.5.5=py38haa95532_0
  - ninja=1.10.2=haa95532_5
  - ninja-base=1.10.2=h6d14046_5
  - notebook=6.4.11=py38haa95532_0
  - numpy=1.21.5=py38h7a0a035_2
  - numpy-base=1.21.5=py38hca35cd5_2
  - opencv=4.0.1=py38h2a7c758_0
  - openssl=1.1.1n=h2bbff1b_0
  - packaging=21.3=pyhd8ed1ab_0
  - pandocfilters=1.5.0=pyhd3eb1b0_0
  - parso=0.8.3=pyhd3eb1b0_0
  - pickleshare=0.7.5=pyhd3eb1b0_1003
  - pillow=9.0.1=py38hdc2b20a_0
  - pip=21.2.2=py38haa95532_0
  - prometheus_client=0.13.1=pyhd3eb1b0_0
  - prompt-toolkit=3.0.20=pyhd3eb1b0_0
  - prompt_toolkit=3.0.20=hd3eb1b0_0
  - pure_eval=0.2.2=pyhd3eb1b0_0
  - py-opencv=4.0.1=py38he44ac1e_0
  - pycparser=2.21=pyhd3eb1b0_0
  - pygments=2.11.2=pyhd3eb1b0_0
  - pyopenssl=22.0.0=pyhd3eb1b0_0
  - pyparsing=3.0.8=pyhd8ed1ab_0
  - pyqt=5.9.2=py38hd77b12b_6
  - pyqt5-sip=4.19.18=py38h885f38d_8
  - pyrsistent=0.18.0=py38h196d8e1_0
  - pysocks=1.7.1=py38haa95532_0
  - python=3.8.13=h6244533_0
  - python-dateutil=2.8.2=pyhd8ed1ab_0
  - python-fastjsonschema=2.15.1=pyhd3eb1b0_0
  - python_abi=3.8=2_cp38
  - pytorch=1.11.0=py3.8_cuda11.3_cudnn8_0
  - pytorch-mutex=1.0=cuda
  - pywin32=302=py38h2bbff1b_2
  - pywinpty=2.0.2=py38h5da7b33_0
  - pyyaml=6.0=py38h294d835_4
  - pyzmq=22.3.0=py38hd77b12b_2
  - qt=5.9.7=vc14h73c81de_0
  - qtconsole=5.3.0=pyhd3eb1b0_0
  - qtpy=2.0.1=pyhd3eb1b0_0
  - requests=2.27.1=pyhd3eb1b0_0
  - send2trash=1.8.0=pyhd3eb1b0_1
  - setuptools=61.2.0=py38haa95532_0
  - sip=4.19.13=py38hd77b12b_0
  - six=1.16.0=pyhd3eb1b0_1
  - soupsieve=2.3.1=pyhd3eb1b0_0
  - sqlite=3.38.3=h2bbff1b_0
  - stack_data=0.2.0=pyhd3eb1b0_0
  - terminado=0.13.1=py38haa95532_0
  - testpath=0.5.0=pyhd3eb1b0_0
  - tk=8.6.11=h2bbff1b_0
  - torchaudio=0.11.0=py38_cu113
  - torchvision=0.12.0=py38_cu113
  - tornado=6.1=py38h294d835_3
  - tqdm=4.64.0=pyhd8ed1ab_0
  - traitlets=5.1.1=pyhd3eb1b0_0
  - typing-extensions=4.1.1=hd3eb1b0_0
  - typing_extensions=4.1.1=pyh06a4308_0
  - unicodedata2=14.0.0=py38h294d835_1
  - urllib3=1.26.9=py38haa95532_0
  - vc=14.2=h21ff451_1
  - vs2015_runtime=14.27.29016=h5e58377_2
  - wcwidth=0.2.5=pyhd3eb1b0_0
  - webencodings=0.5.1=py38_1
  - wheel=0.37.1=pyhd3eb1b0_0
  - widgetsnbextension=3.5.2=py38haa95532_0
  - win_inet_pton=1.1.0=py38haa95532_0
  - wincertstore=0.2=py38haa95532_2
  - winpty=0.4.3=4
  - xz=5.2.5=h8cc25b3_1
  - yaml=0.2.5=h8ffe710_2
  - zipp=3.7.0=pyhd3eb1b0_0
  - zlib=1.2.11=h8ffe710_1014
  - zstd=1.4.9=h19a0ad4_0
prefix: C:\Users\nhadd\anaconda3\envs\semantic-segmentation
